version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PigkitAdmin123
      MYSQL_DATABASE: pigkit
      MYSQL_USER: pigkitadmin
      MYSQL_PASSWORD: PigkitAdmin123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: pigkitadmin
      MINIO_ROOT_PASSWORD: PigkitAdmin123
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  minio-data: