server:
  host: "127.0.0.1"
  port: 8080

database:
  driver: mysql
  host: localhost
  port: 3306
  user: admin
  password: admin
  dbname: xxx

app:
  id: "xxx"
  name: "xxx"
  secret: "xxx" # 小程序官网secret
  jwt_secret: "xxx=" #随机生成
log: