// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "wty92911",
            "url": "https://github.com/wty92911",
            "email": "2066946886@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/family": {
            "get": {
                "description": "获取所有家庭的列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "family"
                ],
                "summary": "获得所有家庭",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.Family"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/family/create": {
            "post": {
                "description": "创建一个新的家庭",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "family"
                ],
                "summary": "创建家庭",
                "parameters": [
                    {
                        "type": "string",
                        "description": "家庭名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.Family"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/family/details": {
            "get": {
                "description": "获取指定家庭的详细信息，包括可选的预加载项",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "family"
                ],
                "summary": "获得家庭详细情况",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "家庭ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "预加载项",
                        "name": "preloads",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.Family"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/family/join": {
            "post": {
                "description": "加入一个现有的家庭",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "family"
                ],
                "summary": "加入家庭",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "家庭ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.Family"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户使用微信登录，后端绑定微信账户并返回JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "后端绑定微信登陆, 返回token",
                "parameters": [
                    {
                        "description": "微信登录请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controller.WeChatLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_wty92911_GoPigKit_internal_model.Category": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "family_id": {
                    "type": "integer"
                },
                "foods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.Food"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "mid_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "top_name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_wty92911_GoPigKit_internal_model.Family": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.Category"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "menu_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.MenuItem"
                    }
                },
                "name": {
                    "type": "string"
                },
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.Order"
                    }
                },
                "owner_open_id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.User"
                    }
                }
            }
        },
        "github_com_wty92911_GoPigKit_internal_model.Food": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "食品分类ID，外键",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "desc": {
                    "description": "食品描述",
                    "type": "string"
                },
                "family_id": {
                    "description": "家庭ID，外键",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "image_urls": {
                    "description": "食品图片",
                    "type": "string"
                },
                "price": {
                    "description": "食品价格",
                    "type": "integer"
                },
                "title": {
                    "description": "食品名称",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.User"
                }
            }
        },
        "github_com_wty92911_GoPigKit_internal_model.MenuItem": {
            "type": "object",
            "properties": {
                "createdBy": {
                    "type": "string"
                },
                "family_id": {
                    "description": "所属家庭ID",
                    "type": "integer"
                },
                "food_id": {
                    "description": "食品ID",
                    "type": "integer"
                },
                "quantity": {
                    "description": "数量",
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.User"
                }
            }
        },
        "github_com_wty92911_GoPigKit_internal_model.Order": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "family_id": {
                    "description": "家庭ID，外键",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "description": "关联的订单项，联级删除",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.OrderItem"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_wty92911_GoPigKit_internal_model.OrderItem": {
            "type": "object",
            "properties": {
                "createdBy": {
                    "type": "string"
                },
                "food_id": {
                    "description": "食品ID",
                    "type": "integer"
                },
                "order_id": {
                    "description": "订单ID，外键",
                    "type": "integer"
                },
                "quantity": {
                    "description": "数量",
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/github_com_wty92911_GoPigKit_internal_model.User"
                }
            }
        },
        "github_com_wty92911_GoPigKit_internal_model.User": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "description": "Role      string         ` + "`" + `json:\"role\" validate:\"oneof=owner member\"` + "`" + `",
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "family_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "open_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_controller.UserInfo": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "internal_controller.WeChatLoginRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "userInfo": {
                    "$ref": "#/definitions/internal_controller.UserInfo"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API",
	Description:      "初始化路由",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
