basePath: /api/v1
definitions:
  github_com_wty92911_GoPigKit_internal_model.Category:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      family_id:
        type: integer
      foods:
        items:
          $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Food'
        type: array
      id:
        type: integer
      image_url:
        type: string
      mid_name:
        type: string
      name:
        type: string
      top_name:
        type: string
      updatedAt:
        type: string
    required:
    - family_id
    - image_url
    - mid_name
    - name
    - top_name
    type: object
  github_com_wty92911_GoPigKit_internal_model.Family:
    properties:
      categories:
        items:
          $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Category'
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      menu_items:
        items:
          $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.MenuItem'
        type: array
      name:
        type: string
      orders:
        items:
          $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Order'
        type: array
      owner:
        $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.User'
      owner_open_id:
        type: string
      updatedAt:
        type: string
      users:
        items:
          $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.User'
        type: array
    required:
    - name
    type: object
  github_com_wty92911_GoPigKit_internal_model.Food:
    properties:
      category_id:
        description: 食品分类ID，外键
        type: integer
      created_by:
        description: 创建者
        type: string
      createdAt:
        type: string
      createdUser:
        $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.User'
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      desc:
        description: 食品描述
        type: string
      id:
        type: integer
      image_urls:
        description: 食品图片
        items:
          type: integer
        type: array
      price:
        description: 食品价格
        type: integer
      title:
        description: 食品名称
        type: string
      updatedAt:
        type: string
    required:
    - category_id
    - created_by
    - image_urls
    - price
    - title
    type: object
  github_com_wty92911_GoPigKit_internal_model.MenuItem:
    properties:
      createdBy:
        type: string
      family_id:
        description: 所属家庭ID
        type: integer
      food_id:
        description: 食品ID
        type: integer
      quantity:
        description: 数量
        type: integer
      user:
        $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.User'
    type: object
  github_com_wty92911_GoPigKit_internal_model.Order:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      family_id:
        description: 家庭ID，外键
        type: integer
      id:
        type: integer
      items:
        description: 关联的订单项，联级删除
        items:
          $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.OrderItem'
        type: array
      updatedAt:
        type: string
    type: object
  github_com_wty92911_GoPigKit_internal_model.OrderItem:
    properties:
      created_by:
        description: 创建者，外键
        type: string
      food_id:
        description: 食品ID
        type: integer
      order_id:
        description: 订单ID，外键
        type: integer
      quantity:
        description: 数量
        type: integer
      user:
        $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.User'
    type: object
  github_com_wty92911_GoPigKit_internal_model.User:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      family_id:
        description: user创建时可以不指定family_id，等后面再加入一个家庭
        type: integer
      name:
        type: string
      open_id:
        type: string
      updated_at:
        type: string
    required:
    - name
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  internal_controller.ErrMsg:
    enum:
    - invalid param
    type: string
    x-enum-varnames:
    - InvalidParam
  internal_controller.UserInfo:
    properties:
      avatar_url:
        type: string
      nickname:
        type: string
    type: object
  internal_controller.WeChatLoginRequest:
    properties:
      code:
        type: string
      userInfo:
        $ref: '#/definitions/internal_controller.UserInfo'
    required:
    - code
    type: object
host: localhost:8080
info:
  contact:
    email: 2066946886@qq.com
    name: wty92911
    url: https://github.com/wty92911
  description: 初始化路由
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: API
  version: "1.0"
paths:
  /api/v1/categories:
    get:
      description: 获取所有分类的列表
      parameters:
      - description: 家庭ID
        in: query
        name: family_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Category'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: 获得所有分类
      tags:
      - category
  /api/v1/category:
    post:
      consumes:
      - multipart/form-data
      description: 创建分类,包括分类的三级名称、图片，返回创建好的分类+图片链接
      parameters:
      - description: 家庭ID
        in: body
        name: family_id
        required: true
        schema:
          type: integer
      - description: 顶级分类名称
        in: body
        name: top_name
        required: true
        schema:
          type: string
      - description: 中间分类名称
        in: body
        name: mid_name
        required: true
        schema:
          type: string
      - description: 分类名称
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: 图片链接
        in: body
        name: image_url
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Category'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 创建分类
      tags:
      - category
  /api/v1/category/{id}:
    delete:
      description: 根据删除分类
      parameters:
      - description: 分类ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller.ErrMsg'
      summary: 删除分类
      tags:
      - category
  /api/v1/family:
    get:
      description: 获取所有家庭的列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Family'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: 获得所有家庭
      tags:
      - family
  /api/v1/family/create:
    post:
      description: 创建一个新的家庭
      parameters:
      - description: 家庭名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Family'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller.ErrMsg'
        "500":
          description: Internal Server Error
          schema: {}
      summary: 创建家庭
      tags:
      - family
  /api/v1/family/details:
    get:
      description: 获取指定家庭的详细信息，包括可选的预加载项
      parameters:
      - description: 家庭ID
        in: query
        name: id
        required: true
        type: integer
      - collectionFormat: csv
        description: 预加载项
        in: query
        items:
          type: string
        name: preloads
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Family'
        "500":
          description: Internal Server Error
          schema: {}
      summary: 获得家庭详细情况
      tags:
      - family
  /api/v1/family/join:
    post:
      description: 加入一个现有的家庭
      parameters:
      - description: 家庭ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Family'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller.ErrMsg'
        "500":
          description: Internal Server Error
          schema: {}
      summary: 加入家庭
      tags:
      - family
  /api/v1/food:
    post:
      consumes:
      - application/json
      description: 创建食品，返回创建好的食品
      parameters:
      - description: 创建食品请求参数
        in: body
        name: food
        required: true
        schema:
          $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Food'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Food'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 创建食品
      tags:
      - food
  /api/v1/foods:
    get:
      description: 根据分类ID获取食物列表
      parameters:
      - description: 分类ID
        in: query
        name: category_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.Food'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: 根据分类获取食物
      tags:
      - food
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 用户使用微信登录，后端绑定微信账户并返回JWT token
      parameters:
      - description: 微信登录请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_controller.WeChatLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 后端绑定微信登陆, 返回token
      tags:
      - auth
  /api/v1/upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传文件
      parameters:
      - description: 上传文件
        in: formData
        name: file
        required: true
        type: file
      - description: 文件路径
        in: formData
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: url
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller.ErrMsg'
        "500":
          description: Internal Server Error
          schema: {}
      summary: 上传文件
      tags:
      - file
  /api/v1/users:
    get:
      description: 获取所有用户的列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_wty92911_GoPigKit_internal_model.User'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: 获得所有用户
      tags:
      - user
swagger: "2.0"
